### ISSUE TITLE
cupsd crash reported frequently by automatic crash reporting system of Ubuntu

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5085]
Ubuntu has an automatic crash reporting system where, when a crash happens, after a short click-through confirmation of the user, the crash-relevant data, especially the dumped core, is sent to Canonical and put into a database, especially joining/counting incidents which seem to come from the same type of crash.

There are very frequent reports (around 20 per day) of the crash leading to the stack trace shown below.

It seems that it is tried to free a corrupted (or non-existing) Avahi entry group. The avahi_entry_group_free() function (step #4) checks consistency with the assert() function (bad practice !!!) and aborts on something like "assert(*_head == _item)" (step #2).

This is rather annoying due to the crash report pop-ups appearing for the users.

Note that to protect user's privacy, the crash tracking system is not public and the reports are anonymised. So one cannot ask the users for further information.

```
Stacktrace

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
        set = {__val = {18446744067266838239, 140066000845160, 140066000848640, 140066075430990, 4222451712, 140065862846752, 140065862846752, 140065862846752, 140065862846752, 140065862846837, 140065862846852, 140065862846752, 140065862846852, 0, 0, 0}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007f63aca7c37a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7f63a839bac0, sa_sigaction = 0x7f63a839bac0}, sa_mask = {__val = {140066099388447, 140066000845200, 4, 942881331, 140066101522432, 140066086223506, 245, 140066086224144, 140066000845856, 140066000848640, 140066075488556, 140066076581664, 140066076567336, 7310594991672619630, 140066076567336, 140066086223506}}, sa_flags = -1371934720, sa_restorer = 0x7f63ad507e92}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f63aca72b47 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7f63ad507e92 "*_head == _item", file=file@entry=0x7f63ad507e77 "entrygroup.c", line=line@entry=245, function=function@entry=0x7f63ad508110 <__PRETTY_FUNCTION__.5630> "avahi_entry_group_free") at assert.c:92
        str = 0x7f63a0000920 ""
        total = 4096
#3  0x00007f63aca72bf2 in __GI___assert_fail (assertion=assertion@entry=0x7f63ad507e92 "*_head == _item", file=file@entry=0x7f63ad507e77 "entrygroup.c", line=line@entry=245, function=function@entry=0x7f63ad508110 <__PRETTY_FUNCTION__.5630> "avahi_entry_group_free") at assert.c:101
No locals.
#4  0x00007f63ad501a07 in avahi_entry_group_free (group=0x560ffa2d50f0) at entrygroup.c:245
        _head = 0x560ffa2d4188
        _item = 0x560ffa2d50f0
        client = 0x560ffa2d4130
        r = 0
        __PRETTY_FUNCTION__ = "avahi_entry_group_free"
#5  0x0000560ff93385d2 in dnssdDeregisterInstance (srv=0x560ffa1e20a0, from_callback=<optimized out>) at dirsvc.c:682
No locals.
#6  0x0000560ff9338652 in dnssdDeregisterPrinter (p=0x560ffa1e18c0, clear_name=clear_name@entry=1, from_callback=from_callback@entry=1) at dirsvc.c:709
No locals.
#7  0x0000560ff9338b58 in dnssdDeregisterAllPrinters (from_callback=from_callback@entry=1) at dirsvc.c:657
        p = <optimized out>
#8  0x0000560ff9339f0d in dnssdClientCallback (c=0x560ffa2d4130, state=<optimized out>, userdata=<optimized out>) at dirsvc.c:600
        error = 22031
#9  0x00007f63ad5006e5 in filter_func (bus=<optimized out>, message=0x560ffa1f52f0, userdata=0x560ffa2d4130) at client.c:300
        client = 0x560ffa2d4130
        error = {name = 0x0, message = 0x0, dummy1 = 1, dummy2 = 0, dummy3 = 0, dummy4 = 0, dummy5 = 1, padding1 = 0x7f63ad92863e <_dbus_connection_unlock+62>}
        __PRETTY_FUNCTION__ = "filter_func"
#10 0x00007f63ad92c2a1 in dbus_connection_dispatch (connection=0x560ffa2d4d80) at ../../../dbus/dbus-connection.c:4703
        filter = <optimized out>
        next = 0x0
        message = 0x560ffa1f52f0
        link = <optimized out>
        reply_serial = <optimized out>
        filter_list_copy = 0x560ffa2d68f0
        status = <optimized out>
        found_object = 2900477593
        message_link = 0x560ffa1f35a0
        result = DBUS_HANDLER_RESULT_NOT_YET_HANDLED
        pending = <optimized out>
        connection = 0x560ffa2d4d80
        status = <optimized out>
#11 0x00007f63ad5074d6 in dispatch_timeout_callback (t=<optimized out>, userdata=0x560ffa2d4870) at ../avahi-common/dbus-watch-glue.c:105
        d = 0x560ffa2d4870
#12 0x00007f63ad7145f8 in avahi_simple_poll_dispatch (s=0x560ffa2d3f00) at simple-watch.c:570
        next_timeout = 0x560ffa2d4580
        w = <optimized out>
        __PRETTY_FUNCTION__ = "avahi_simple_poll_dispatch"
#13 0x00007f63ad7148dd in avahi_simple_poll_loop (s=0x560ffa2d3f00) at simple-watch.c:646
        r = <optimized out>
        __PRETTY_FUNCTION__ = "avahi_simple_poll_loop"
#14 0x00007f63ad7149a4 in thread (userdata=0x560ffa1f4740) at thread-watch.c:71
        p = 0x560ffa1f4740
        mask = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}
#15 0x00007f63ace136da in start_thread (arg=0x7f63a839c700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7f63a839c700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140066000848640, 7545561659510713588, 140723272591838, 140723272591839, 140066000849344, 140066000848640, -7606465238569751308, -7606472450053018380}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#16 0x00007f63acb4d17f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
No locals.


Thread Stacktrace
.
Thread 2 (Thread 0x7f63ae2e6d40 (LWP 951)):
#0  __lll_unlock_wake () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:371
No locals.
#1  0x00007f63ace1764f in __pthread_mutex_unlock_usercnt (decr=1, mutex=0x560ffa1f4750) at pthread_mutex_unlock.c:55
        type = <optimized out>
#2  __GI___pthread_mutex_unlock (mutex=0x560ffa1f4750) at pthread_mutex_unlock.c:324
No locals.
#3  0x00007f63ad714d35 in avahi_threaded_poll_unlock (p=<optimized out>) at thread-watch.c:185
        __PRETTY_FUNCTION__ = "avahi_threaded_poll_unlock"
#4  0x0000560ff9338609 in dnssdDeregisterInstance (srv=0x560ffa1e20a0, from_callback=<optimized out>) at dirsvc.c:685
No locals.
#5  0x0000560ff9338652 in dnssdDeregisterPrinter (p=0x560ffa1e18c0, clear_name=clear_name@entry=1, from_callback=from_callback@entry=0) at dirsvc.c:709
No locals.
#6  0x0000560ff9338b58 in dnssdDeregisterAllPrinters (from_callback=from_callback@entry=0) at dirsvc.c:657
        p = <optimized out>
#7  0x0000560ff933a24f in cupsdStopBrowsing () at dirsvc.c:263
No locals.
#8  0x0000560ff9355de5 in cupsdStopServer () at server.c:107
No locals.
#9  0x0000560ff932561d in main (argc=<optimized out>, argv=<optimized out>) at main.c:1166
        i = 2
        opt = <optimized out>
        close_all = <optimized out>
        disconnect = <optimized out>
        fg = <optimized out>
        run_as_child = <optimized out>
        print_profile = <optimized out>
        fds = -1
        con = <optimized out>
        job = <optimized out>
        lis = <optimized out>
        current_time = <optimized out>
        activity = <optimized out>
        senddoc_time = 1490222291
        expire_time = 1490222294
        report_time = 1490222291
        event_time = 1490221894
        timeout = <optimized out>
        limit = {rlim_cur = 4096, rlim_max = 4096}
        action = {__sigaction_handler = {sa_handler = 0x560ff933b330 <sigterm_handler>, sa_sigaction = 0x560ff933b330 <sigterm_handler>}, sa_mask = {__val = {81920, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x0}
        netif_time = 1490222291
        service_idle_exit = <optimized out>
.
Thread 1 (Thread 0x7f63a839c700 (LWP 1650)):
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:58
        set = {__val = {18446744067266838239, 140066000845160, 140066000848640, 140066075430990, 4222451712, 140065862846752, 140065862846752, 140065862846752, 140065862846752, 140065862846837, 140065862846852, 140065862846752, 140065862846852, 0, 0, 0}}
        pid = <optimized out>
        tid = <optimized out>
#1  0x00007f63aca7c37a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x7f63a839bac0, sa_sigaction = 0x7f63a839bac0}, sa_mask = {__val = {140066099388447, 140066000845200, 4, 942881331, 140066101522432, 140066086223506, 245, 140066086224144, 140066000845856, 140066000848640, 140066075488556, 140066076581664, 140066076567336, 7310594991672619630, 140066076567336, 140066086223506}}, sa_flags = -1371934720, sa_restorer = 0x7f63ad507e92}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f63aca72b47 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x7f63ad507e92 "*_head == _item", file=file@entry=0x7f63ad507e77 "entrygroup.c", line=line@entry=245, function=function@entry=0x7f63ad508110 <__PRETTY_FUNCTION__.5630> "avahi_entry_group_free") at assert.c:92
        str = 0x7f63a0000920 ""
        total = 4096
#3  0x00007f63aca72bf2 in __GI___assert_fail (assertion=assertion@entry=0x7f63ad507e92 "*_head == _item", file=file@entry=0x7f63ad507e77 "entrygroup.c", line=line@entry=245, function=function@entry=0x7f63ad508110 <__PRETTY_FUNCTION__.5630> "avahi_entry_group_free") at assert.c:101
No locals.
#4  0x00007f63ad501a07 in avahi_entry_group_free (group=0x560ffa2d50f0) at entrygroup.c:245
        _head = 0x560ffa2d4188
        _item = 0x560ffa2d50f0
        client = 0x560ffa2d4130
        r = 0
        __PRETTY_FUNCTION__ = "avahi_entry_group_free"
#5  0x0000560ff93385d2 in dnssdDeregisterInstance (srv=0x560ffa1e20a0, from_callback=<optimized out>) at dirsvc.c:682
No locals.
#6  0x0000560ff9338652 in dnssdDeregisterPrinter (p=0x560ffa1e18c0, clear_name=clear_name@entry=1, from_callback=from_callback@entry=1) at dirsvc.c:709
No locals.
#7  0x0000560ff9338b58 in dnssdDeregisterAllPrinters (from_callback=from_callback@entry=1) at dirsvc.c:657
        p = <optimized out>
#8  0x0000560ff9339f0d in dnssdClientCallback (c=0x560ffa2d4130, state=<optimized out>, userdata=<optimized out>) at dirsvc.c:600
        error = 22031
#9  0x00007f63ad5006e5 in filter_func (bus=<optimized out>, message=0x560ffa1f52f0, userdata=0x560ffa2d4130) at client.c:300
        client = 0x560ffa2d4130
        error = {name = 0x0, message = 0x0, dummy1 = 1, dummy2 = 0, dummy3 = 0, dummy4 = 0, dummy5 = 1, padding1 = 0x7f63ad92863e <_dbus_connection_unlock+62>}
        __PRETTY_FUNCTION__ = "filter_func"
#10 0x00007f63ad92c2a1 in dbus_connection_dispatch (connection=0x560ffa2d4d80) at ../../../dbus/dbus-connection.c:4703
        filter = <optimized out>
        next = 0x0
        message = 0x560ffa1f52f0
        link = <optimized out>
        reply_serial = <optimized out>
        filter_list_copy = 0x560ffa2d68f0
        status = <optimized out>
        found_object = 2900477593
        message_link = 0x560ffa1f35a0
        result = DBUS_HANDLER_RESULT_NOT_YET_HANDLED
        pending = <optimized out>
        connection = 0x560ffa2d4d80
        status = <optimized out>
#11 0x00007f63ad5074d6 in dispatch_timeout_callback (t=<optimized out>, userdata=0x560ffa2d4870) at ../avahi-common/dbus-watch-glue.c:105
        d = 0x560ffa2d4870
#12 0x00007f63ad7145f8 in avahi_simple_poll_dispatch (s=0x560ffa2d3f00) at simple-watch.c:570
        next_timeout = 0x560ffa2d4580
        w = <optimized out>
        __PRETTY_FUNCTION__ = "avahi_simple_poll_dispatch"
#13 0x00007f63ad7148dd in avahi_simple_poll_loop (s=0x560ffa2d3f00) at simple-watch.c:646
        r = <optimized out>
        __PRETTY_FUNCTION__ = "avahi_simple_poll_loop"
#14 0x00007f63ad7149a4 in thread (userdata=0x560ffa1f4740) at thread-watch.c:71
        p = 0x560ffa1f4740
        mask = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}
#15 0x00007f63ace136da in start_thread (arg=0x7f63a839c700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7f63a839c700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140066000848640, 7545561659510713588, 140723272591838, 140723272591839, 140066000849344, 140066000848640, -7606465238569751308, -7606472450053018380}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#16 0x00007f63acb4d17f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
No locals.
```

**Comment by michaelrsweet** [comment]
[master b337f966e] Fix an Avahi-related crash bug in the scheduler (Issue #5085, Issue #5086)
