### ISSUE TITLE
discovered by automatic crash tracker: NULL check needed for avahi_group_free() call in cupsd

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5086]
This is also reported by Ubuntu users around 20 times per day, according to the automatic crash tracker (see issue #5085):

When avahi_group_free() it can happen that the supplied group is NULL and avahi_group_free() aborts the program via an assert() call. See stacktrace below.

It is trivial to fix by replacing all avahi_group_free(group) calls in cupsd by

if (group) avahi_group_free(group)

```
Stacktrace

#0  avahi_entry_group_free (group=0x0) at entrygroup.c:242
        client = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "avahi_entry_group_free"
#1  0x00005598ee92d600 in dnssdDeregisterInstance (srv=0x5598ef8406c0, from_callback=<optimized out>) at dirsvc.c:682
No locals.
#2  0x00005598ee92d652 in dnssdDeregisterPrinter (p=0x5598ef83fee0, clear_name=clear_name@entry=1, from_callback=from_callback@entry=0) at dirsvc.c:709
No locals.
#3  0x00005598ee92db58 in dnssdDeregisterAllPrinters (from_callback=from_callback@entry=0) at dirsvc.c:657
        p = <optimized out>
#4  0x00005598ee92f24f in cupsdStopBrowsing () at dirsvc.c:263
No locals.
#5  0x00005598ee94af25 in cupsdStopServer () at server.c:107
No locals.
#6  0x00005598ee91a61d in main (argc=<optimized out>, argv=<optimized out>) at main.c:1166
        i = 2
        opt = <optimized out>
        close_all = <optimized out>
        disconnect = <optimized out>
        fg = <optimized out>
        run_as_child = <optimized out>
        print_profile = <optimized out>
        fds = -1
        con = <optimized out>
        job = <optimized out>
        lis = <optimized out>
        current_time = <optimized out>
        activity = <optimized out>
        senddoc_time = 1491476201
        expire_time = 1491476201
        report_time = 1491476201
        event_time = 1491471330
        timeout = <optimized out>
        limit = {rlim_cur = 4096, rlim_max = 4096}
        action = {__sigaction_handler = {sa_handler = 0x5598ee930470 <sigterm_handler>, sa_sigaction = 0x5598ee930470 <sigterm_handler>}, sa_mask = {__val = {81920, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x0}
        netif_time = 1491476201
        service_idle_exit = <optimized out>
Thread Stacktrace

.
Thread 2 (Thread 0x7fe7a062f700 (LWP 2517)):
#0  __lll_unlock_wake () at ../sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:371
No locals.
#1  0x00007fe7a50aa64f in __pthread_mutex_unlock_usercnt (decr=1, mutex=mutex@entry=0x5598ef938e00) at pthread_mutex_unlock.c:55
        type = <optimized out>
#2  __GI___pthread_mutex_unlock (mutex=mutex@entry=0x5598ef938e00) at pthread_mutex_unlock.c:324
No locals.
#3  0x00007fe7a59a793d in poll_func (ufds=0x7fe7980008c0, nfds=2, timeout=0, userdata=0x5598ef938e00) at thread-watch.c:55
        mutex = 0x5598ef938e00
#4  0x00007fe7a59a74d3 in avahi_simple_poll_run (s=0x5598ef936ed0) at simple-watch.c:527
        s = 0x5598ef936ed0
#5  0x00007fe7a59a76a8 in avahi_simple_poll_iterate (s=0x5598ef936ed0, timeout=<optimized out>) at simple-watch.c:602
        r = <optimized out>
#6  0x00007fe7a59a78dd in avahi_simple_poll_loop (s=0x5598ef936ed0) at simple-watch.c:646
        r = <optimized out>
        __PRETTY_FUNCTION__ = "avahi_simple_poll_loop"
#7  0x00007fe7a59a79a4 in thread (userdata=0x5598ef938df0) at thread-watch.c:71
        p = 0x5598ef938df0
        mask = {__val = {18446744067267100671, 18446744073709551615 <repeats 15 times>}}
#8  0x00007fe7a50a66da in start_thread (arg=0x7fe7a062f700) at pthread_create.c:456
        __res = <optimized out>
        pd = 0x7fe7a062f700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140632805013248, -262733765689546808, 140721920509406, 140721920509407, 140632805013952, 140632805013248, 258347633894156232, 258357869100459976}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#9  0x00007fe7a4de017f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
No locals.
.
Thread 1 (Thread 0x7fe7a6579d40 (LWP 2496)):
#0  avahi_entry_group_free (group=0x0) at entrygroup.c:242
        client = <optimized out>
        r = <optimized out>
        __PRETTY_FUNCTION__ = "avahi_entry_group_free"
#1  0x00005598ee92d600 in dnssdDeregisterInstance (srv=0x5598ef8406c0, from_callback=<optimized out>) at dirsvc.c:682
No locals.
#2  0x00005598ee92d652 in dnssdDeregisterPrinter (p=0x5598ef83fee0, clear_name=clear_name@entry=1, from_callback=from_callback@entry=0) at dirsvc.c:709
No locals.
#3  0x00005598ee92db58 in dnssdDeregisterAllPrinters (from_callback=from_callback@entry=0) at dirsvc.c:657
        p = <optimized out>
#4  0x00005598ee92f24f in cupsdStopBrowsing () at dirsvc.c:263
No locals.
#5  0x00005598ee94af25 in cupsdStopServer () at server.c:107
No locals.
#6  0x00005598ee91a61d in main (argc=<optimized out>, argv=<optimized out>) at main.c:1166
        i = 2
        opt = <optimized out>
        close_all = <optimized out>
        disconnect = <optimized out>
        fg = <optimized out>
        run_as_child = <optimized out>
        print_profile = <optimized out>
        fds = -1
        con = <optimized out>
        job = <optimized out>
        lis = <optimized out>
        current_time = <optimized out>
        activity = <optimized out>
        senddoc_time = 1491476201
        expire_time = 1491476201
        report_time = 1491476201
        event_time = 1491471330
        timeout = <optimized out>
        limit = {rlim_cur = 4096, rlim_max = 4096}
        action = {__sigaction_handler = {sa_handler = 0x5598ee930470 <sigterm_handler>, sa_sigaction = 0x5598ee930470 <sigterm_handler>}, sa_mask = {__val = {81920, 0 <repeats 15 times>}}, sa_flags = 0, sa_restorer = 0x0}
        netif_time = 1491476201
        service_idle_exit = <optimized out>
```

**Comment by michaelrsweet** [comment]
[master b337f966e] Fix an Avahi-related crash bug in the scheduler (Issue #5085, Issue #5086)
