### ISSUE TITLE
IPP crashes after every successfully completed job since 2.4.2

### ISSUE THREAD

**Issue by Nils-TUD** [apple/cups#6041]
Since I upgraded to CUPS 2.4.2, the IPP backend crashes every time after the print is complete. Therefore, I need to manually cancel the job and resume the printer afterwards. I just downgraded to 2.4.1 again and there it still works.

That's the output from `coredumpctl gdb`:
```
           PID: 97441 (ipp)
           UID: 0 (root)
           GID: 209 (cups)
        Signal: 11 (SEGV)
     Timestamp: Mon 2022-06-06 07:52:30 CEST (5min ago)
  Command Line: ipp://EPSON482791.local:631/ipp/print 1689 hrniels $'71dYmWUxnrL._AC_SY355_.jpg (870×355)' 1 $'printer-state-reasons=cups-ipp-conformance-failure-report,cups-ipp-missing-job-history printer-is-accepting-jobs PageSize=A4 marker-types=ink,ink,ink,ink noprinter-is-shared marker-low-levels=15,15,15,15 marker-colors=#000000,#00FFFF,#FF00FF,#FFFF00 Ink=COLOR printer-location= marker-levels=68,81,81,81 Duplex=None Collate marker-change-time=1654411089 marker-names=Black\\\\\\ ink,Cyan\\\\\\ ink,Magenta\\\\\\ ink,Yellow\\\\\\ ink printer-state=3 device-uri=dnssd://EPSON%20ET-2750%20Series._ipp._tcp.local/?uuid=cfe92100-67c4-11d4-a45f-e0bb9e482791 printer-uri-supported=ipp://localhost/printers/EPSON_ET-2750_Series print-color-mode=color printer-type=2101276 printer-commands=none printer-state-change-time=1654411111 noprinter-is-temporary number-up=1 finishings=3 marker-high-levels=100,100,100,100 job-uuid=urn:uuid:19b1785f-caee-37f4-77ce-5f292ae8174f job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1654494684 time-at-processing=1654494684'
    Executable: /usr/lib/cups/backend/ipp
 Control Group: /system.slice/cups.service
          Unit: cups.service
         Slice: system.slice
       Boot ID: 1d9fce640ed146239ea60ceb88da24df
    Machine ID: 6531e9b368734d409b8b553b97dc4b2d
      Hostname: hrniels-home
       Storage: /var/lib/systemd/coredump/core.ipp.0.1d9fce640ed146239ea60ceb88da24df.97441.1654494750000000.zst (present)
     Disk Size: 334.3K
       Message: Process 97441 (ipp) of user 0 dumped core.
                
                Module linux-vdso.so.1 with build-id 4bbdd9447359021631434950a65998efe247ea02
                Module libresolv.so.2 with build-id 89a368a6ad1b392d126a2a5beb9c2f61ade00279
                Module libnss_mdns_minimal.so.2 with build-id 8eb55de0d3252a36920a5d74c2da924a902cfff4
                Module libnss_resolve.so.2 with build-id 1790ccea3fad28777fc366683fe31ed6581c9446
                Module libnss_mymachines.so.2 with build-id 51b4a7127dac7bcef5aa6e3046e0509069dcba00
                Module libgpg-error.so.0 with build-id f9aaa96d5ddf6f6872051ed7abcdfe6bdaff9b1c
                Module libgcc_s.so.1 with build-id 0e3de903950e35ae59a5de8c00b1817a4a71ca01
                Module liblz4.so.1 with build-id e63600ab23b2f6997f42fac2fa56e1f02ce159a1
                Module libzstd.so.1 with build-id 3bccb8fe08e48d5ea135b1d0f99de0d771dd752f
                Module liblzma.so.5 with build-id 28b40c7af8098a66af6ee093b6986b91cad7694d
                Module libgcrypt.so.20 with build-id 8bf3cb884124273640de797a3e77d86c98434ea4
                Module libcap.so.2 with build-id 21b00ab76bb16fde56fd741f07233c78069f0579
                Module libsystemd.so.0 with build-id a220b34e873e29bb116d88be0bf11fac7089ef4d
                Module libdl.so.2 with build-id 94198b268228074fa9f405bbedbbae94112593ed
                Module libdbus-1.so.3 with build-id 7f4b16b4b407cbae2d7118d6f99610e29a18a56a
                Module libpthread.so.0 with build-id 95ae4f30a6f12ccbff645d30f8e1a3ee23ec7d36
                Module ld-linux-x86-64.so.2 with build-id fc93487393eea02b5bc6e76e48976fc325294c24
                Module libm.so.6 with build-id 210ec9905e41825671210f8f7d0b24d6c371196a
                Module libz.so.1 with build-id fefe3219a96d682ec98fcfb78866b8594298b5a2
                Module libcrypto.so.1.1 with build-id d54a7ee1e288aeae436d073277ff986e03994b15
                Module libssl.so.1.1 with build-id 25a55106cb13dec5d495c34ca1caf2c2f3114f11
                Module libavahi-client.so.3 with build-id 1858551543958190c653b565cf0eb64609ad908a
                Module libavahi-common.so.3 with build-id 80fda945459a3476ccd1050783dfd5f5c17c479a
                Module libc.so.6 with build-id 388993b6ef62f964bc7bf473c069fbfe957b9e44
                Module libcups.so.2 with build-id 13528a932d9dc7086b873307c702513bed51ec79
                Module ipp with build-id fb58924e9ec8d89716c82b45f50d06b238301e73
                Stack trace of thread 97441:
                #0  0x00007f3fef9fec60 n/a (libc.so.6 + 0x1fec60)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/cups/backend/ipp...
(No debugging symbols found in /usr/lib/cups/backend/ipp)
[New LWP 97441]
[New LWP 97588]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `ipp://EPSON482791.local:631/ipp/print 1689 hrniels 71dYmWUxnrL._AC_SY355_.jpg ('.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f3fef9fec60 in ?? () from /usr/lib/libc.so.6
[Current thread is 1 (Thread 0x7f3feefcf7c0 (LWP 97441))]
(gdb) bt
#0  0x00007f3fef9fec60 in ?? () from /usr/lib/libc.so.6
#1  0x00007f3fefa9dd2a in _httpTLSStop () from /usr/lib/libcups.so.2
#2  0x00007f3fefa8cdf9 in httpReconnect2 () from /usr/lib/libcups.so.2
#3  0x00007f3fefaa66d0 in cupsSendRequest () from /usr/lib/libcups.so.2
#4  0x00007f3fefaa695c in cupsDoIORequest () from /usr/lib/libcups.so.2
#5  0x000055e93eb28c2d in ?? ()
#6  0x00007f3fef829290 in ?? () from /usr/lib/libc.so.6
#7  0x00007f3fef82934a in __libc_start_main () from /usr/lib/libc.so.6
#8  0x000055e93eb2a865 in ?? ()
```

`uname -a`:
```Linux hrniels-home 5.18.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 30 May 2022 17:53:11 +0000 x86_64 GNU/Linux```

**Comment by Nils-TUD** [comment]
Sorry, I just noticed that I reported this issue in the wrong repo. I reported it again [here](https://github.com/OpenPrinting/cups/issues/409). Since the git history and version numbers look pretty different, I assume that the issue does not exist in this repo.
